#!bin/bash
clear
red='\e[1;31m'
green='\e[1;32m'
blue='\e[1;34m'
purple='\e[1;35m'
cyan='\e[1;36m'
white='\e[1;37m'
yellow='\e[1;33m'

apt install python -y
apt install python2 -y
ap install python2.7 -y 
apt installl nmap -y
apt install tcpdump -y 
apt install figlet -y 
apt install toilet -y
gem install lolcat
pip2 install scapy

git clone https://github.com/websploit/websploit
cd websploit
python2 websploit
